name: contexts

on:
  push:
    branches:
    - main

jobs:
  my-context:
    runs-on: ubuntu-latest
    steps:
      - name: "My step"
        env:
          MY_ACTION: ${{github.action}}
        run: |
          echo "$MY_ACTION"
          echo " ${{github.action_path}}"
          echo " ${{github.action_ref	}}"
          echo " ${{github.workspace	}}"
          echo " ${{github.workflow_sha	}}"
          echo " ${{github.workflow_ref	}}"
          echo " ${{github.workflow	}}"
          echo " ${{github.triggering_actor	}}"
          echo " ${{github.token	}}"
          echo " ${{github.sha	}}"
          echo " ${{github.server_url	}}"
          echo " ${{github.secret_source	}}"
          echo " ${{github.run_attempt	}}"
          echo " ${{github.run_number	}}"
          echo " ${{github.run_id}}"
          echo " ${{github.retention_days	}}"
          echo " ${{ github.repositoryUrl	 }}"
          echo " ${{ github.repository_owner_id	 }}"
          echo " ${{ github.repository_owner	 }}"
          echo " ${{ github.repository_id	 }}"
          echo " ${{ github.repository }}"
          echo " ${{ github.ref_type	 }}"
          echo " ${{ github.ref_protected	 }}"
          echo " ${{ github.ref_name	 }}"
          echo " ${{ github.ref	 }}"
          echo " ${{ github.path	 }}"
          echo " ${{ github.job	 }}"
          echo " ${{ github.head_ref	 }}"
          echo " ${{ github.graphql_url	 }}"
          echo " ${{ github.event_path	 }}"
          echo " ${{  github.event_name	}}"
          echo " ${{ github.event	 }}"
          echo " ${{ github.env	 }}"
          echo " ${{ github.base_ref	 }}"
          echo " ${{ github.api_url	 }}"
          echo " ${{ github.actor_id	 }}"
          echo " ${{ github.actor }}"
          echo " ${{ github.action_status	 }}"
          echo " ${{ github.action_repository	 }}"
