# If you don't create a self-hosted runner you will see:
# Waiting for a runner to pick up this job...
name: Self-hosted Runner Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Doing some computations
        run: |
          time echo "scale=1000; 4*a(1)" | bc -l

      - name: Run a one-line script
        run: echo "Hello from a self-hosted runner!"